### PR TITLE
Rebase Pip to 21.2.4

### PR DESCRIPTION
**Pull request by cobaltgit**

### CODE REVIEW

**Comment by eht16** [comment]
Thanks.
Only the `PYTHON_GET_PIP_SHA256` needs to be updated as well.

**Comment by cobaltgit** [comment]
Oh, my bad

**Comment by cobaltgit** [comment]
Also, for some reason there's no get-pip.py URL for 21.2.4

**Comment by eht16** [comment]
Yeah, so we should wait with updating Pip until a corresponding "get-pip" version is available.

**Comment by cobaltgit** [comment]
Ok then. Perform another check once get-pip updates to 21.1.4 and if it's good, merge it

**Comment by cobaltgit** [comment]
There's still no get-pip for 21.2.4, so I'd say a last resort would be to just do `pip install -U pip` at the end of the build stage, if that doesn't bloat the image more

**Comment by cobaltgit** [comment]
I brought this up in the official Python Discord server a bit ago, I was told to use `ensurepip` instead. I've heard of it, but not really touched upon it

**Comment by eht16** [comment]
> There's still no get-pip for 21.2.4, so I'd say a last resort would be to just do `pip install -U pip` at the end of the build stage, if that doesn't bloat the image more

This way we lose control over the `pip` version which is installed and also the hash check
We could do `pip install -U pip==X.Y.Z` but we would still lose the hash check.

I would rather keep the way it is currently handled, even if we are a single release behind than upstream.

> I brought this up in the official Python Discord server a bit ago, I was told to use `ensurepip` instead. I've heard of it, but not really touched upon it

`ensurepip` is similar to manually running `pip install -U pip` except that you cannot define the version to install at all. I think it won't help in this case.

**Comment by cobaltgit** [comment]
Yeah. Still nothing

**Comment by cobaltgit** [comment]
UPDATE: get-pip has FINALLY been updated to 21.2.4. Lemme just push and I'll be with you

**Comment by eht16** [comment]
To quote myself from https://github.com/eht16/python3-docker/pull/7#issuecomment-902237941:
>  Only the PYTHON_GET_PIP_SHA256 needs to be updated as well.

But there are many more commits in this branch and especially the CI commits are unrelated. Would you mind to rebase your branch and remove all unrelated commits? Ideally, there will be only one commit left to update the Pip version.

**Comment by eht16** [comment]
@cobaltgit I hope you don't mind, I updated Pip myself together with a bump to Python 3.10.0.

**Pull request closed without merging**
